logan/logan/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^$", views.home, name="home"),
    url(r"^analysis/(?P<id>\d+)/", views.analysis, name="analysis"),
    url(r"^user/(?P<id>\d+)/", views.user, name="user"),
]

logan/logan/models.py
import json
from datetime import datetime, timedelta
from collections import defaultdict

from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse


class Analysis(models.Model):
    class Visibility:
        PUBLIC = "public"
        INTERNAL = "internal"
        PRIVATE = "private"
        CHOICES = (
            (PUBLIC, _("Public")),
            (INTERNAL, _("Internal")),
            (PRIVATE, _("Private")),
        )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    visibility = models.CharField(
        verbose_name=_("Visibility"), max_length=30, choices=Visibility.CHOICES,
        default=Visibility.PRIVATE
    )
    title = models.CharField(verbose_name=_("Title"), max_length=255)
    description = models.TextField(verbose_name=_("Description"), blank=True)
    created = models.DateTimeField(verbose_name=_("Created"), auto_now_add=True)
    modified = models.DateTimeField(verbose_name=_("Modified"), auto_now=True)
    data = JSONField(verbose_name=_("JSON data"))

    class Meta:
        verbose_name = _("Analysis")
        verbose_name_plural = _("Analyses")

    def __str__(self):
        return self.title

    @staticmethod
    def build(queryset, author, visibility=Visibility.PRIVATE):
        analysis = Analysis(
            author=author,
            visibility=visibility,
            title="%s: %s (%s items)" % (author, datetime.now(), queryset.count()),
        )

        references = dict()
        nodes = list()
        ip_dict = defaultdict(list)
        node_type = dict(
            GET="circle",
            POST="square",
            PUT="square",
            PATCH="square",
            HEAD="triangle-up",
            OPTIONS="triangle-down",
            DELETE="cross",
            CONNECT="diamond",
            TRACE="diamond",
        )
        for ref, item in enumerate(queryset.order_by("datetime")):
            references[item] = ref
            node_dict = dict(
                size=max(20, min(200, item.bytes_sent / 500)),
                score=item.status_code,
                id=item.request,
                type=node_type.get(item.verb)
            )
            nodes.append(node_dict)
            ip_dict[item.client_ip_address].append(item)

        links = []
        delta = timedelta(seconds=6)
        for k in ip_dict.keys():
            for i, request_i in enumerate(ip_dict[k][:-1]):

                request_j = ip_dict[k][i + 1]
                if request_j.datetime - request_i.datetime <= delta:

                    links.append(
                        {
                            "source": references[request_i],
                            "target": references[ip_dict[k][i + 1]],
                        }
                    )
                # for j, request_j in enumerate(ip_dict[k][i+1:], i+1):
                #     try:
                #         if request_j.referrer.split('/', 3)[3] == request_i.url.lstrip('/'):
                #             links.append({'source': references[request_i],
                #                           'target': references[request_j]})
                #     except IndexError:
                #         pass

        data = {"directed": True, "multigraph": True, "links": links, "nodes": nodes}

        analysis.data = json.dumps(data)
        analysis.save()

        return analysis

    @property
    def url(self):
        return reverse("analysis", kwargs=dict(id=self.pk))

logan/logan/forms.py
from django import forms

from .models import Analysis


class AnalysisForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
        self.fields["description"].widget.attrs["placeholder"] = "Enter description"
        self.fields["description"].widget.attrs["placeholder"] = "Enter description"

    def make_read_only(self):
        for field in self.fields.values():
            field.widget.attrs["readonly"] = True

    class Meta:
        model = Analysis
        fields = [
            "title",
            "description",
            "visibility",
        ]

logan/logan/views.py
#!/usr/bin/env python
from django.contrib.auth import get_user_model
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect

from .forms import AnalysisForm
from .models import Analysis


def home(request):
    my_analyses = []
    visible_analyses = Analysis.objects.all()

    visibility_filter = Q(visibility=Analysis.Visibility.PUBLIC)
    if request.user.is_authenticated:
        visibility_filter |= Q(visibility=Analysis.Visibility.INTERNAL)
        my_analyses = Analysis.objects.filter(author=request.user)
        visible_analyses = visible_analyses.exclude(author=request.user)

    visible_analyses = visible_analyses.filter(visibility_filter)

    return render(request, "logan/home.html", dict(
        my_analyses=my_analyses,
        visible_analyses=visible_analyses
    ))


def analysis(request, id):
    analysis_object = get_object_or_404(Analysis, id=id)

    if analysis_object.author != request.user:
        if not (analysis_object.visibility == Analysis.Visibility.PUBLIC or (
            analysis_object.visibility == Analysis.Visibility.INTERNAL and
            request.user.is_authenticated
        )):
            raise PermissionDenied

    if request.method == "POST":
        if analysis_object.author != request.user:
            raise PermissionDenied
        analysis_form = AnalysisForm(instance=analysis_object, data=request.POST)
        if analysis_form.is_valid():
            analysis_form.save()
        return redirect("analysis", id)

    analysis_form = None
    if analysis_object.author == request.user:
        analysis_form = AnalysisForm(instance=analysis_object)

    return render(request, "logan/analysis.html", dict(
        analysis=analysis_object,
        form=analysis_form
    ))


def user(request, id):
    user_object = get_object_or_404(get_user_model(), id=id)

    user_analyses = Analysis.objects.filter(author=user_object)

    if user_object != request.user:

        visibility_filter = Q(visibility=Analysis.Visibility.PUBLIC)
        if request.user.is_authenticated:
            visibility_filter |= Q(visibility=Analysis.Visibility.INTERNAL)

        user_analyses = user_analyses.filter(visibility_filter)

    return render(request, "logan/user.html", dict(
        user=user_object,
        analyses=user_analyses
    ))

logan/templates/logan/base.html
{% load static %}
<!DOCTYPE html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% block js %}
    <script src="{% static "node_modules/jquery/dist/jquery.min.js" %}"></script>
    <script src="{% static "node_modules/popper.js/dist/popper.min.js" %}"></script>
    <script src="{% static "node_modules/bootstrap/dist/js/bootstrap.min.js" %}"></script>
  {% endblock js %}

  {% block css %}
    <link href="{% static "node_modules/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "logan/css/base.css" %}" rel="stylesheet">
  {% endblock css %}
</head>


<html>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Logan</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url "home" %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/admin" target="_blank">Admin</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col">

      <div id="content">
        {% block content %}
        {% endblock %}
      </div>

    </div>
  </div>
</div>

logan/templates/logan/home.html
{% extends "logan/base.html" %}
{% load static %}

{% block content %}

  {% if my_analyses %}
    <h1>My Analyses</h1>
    <ul class="list-group">
      {% for analysis in my_analyses %}
        <li class="list-group-item">
          <a href="{% url "analysis" analysis.id %}">{{ analysis }}</a>
          {% if analysis.description %}<p>{{ analysis.description }}</p>{% endif %}
        </li>
      {% endfor %}
    </ul>
    <hr>
  {% endif %}


  {% if visible_analyses %}
    <h1>Visible Analyses</h1>
    <ul class="list-group">
      {% for analysis in visible_analyses %}
        <li class="list-group-item">
          <a href="{% url "analysis" analysis.id %}">{{ analysis }}</a>
          {% if analysis.description %}<p>{{ analysis.description }}</p>{% endif %}
        </li>
      {% endfor %}
    </ul>
  {% endif %}

{% endblock content %}

logan/templates/logan/user.html
{% extends "logan/base.html" %}
{% load static %}

{% block content %}

  <h1>{{ user.username }}</h1>

  <h2>Analyses</h2>

  {% if analyses %}
    <ul class="list-group">
      {% for analysis in analyses %}
        <li class="list-group-item">
          <a href="{% url "analysis" analysis.id %}">{{ analysis }}</a> ({{ analysis.get_visibility_display }})
          {% if analysis.description %}<p>{{ analysis.description }}</p>{% endif %}
        </li>
      {% endfor %}
    </ul>
  {% endif %}

{% endblock content %}